defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- Rakefile
- vendor
plugins:
- jekyll-coffeescript
- jekyll-sitemap
kramdown:
  hard_wrap: false
  input: GFM
permalink: pretty
sass:
  sass_dir: static/styles
timezone: America/Chicago
