%YAML 1.1
---
# https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
lsi: false
pygments: true
safe: true

permalink: pretty
timezone: America/Chicago

config:
    author:
        email: taylor@fausak.me
        facebook_id: 100001771158100
        google_id: +TaylorFausak
        name: Taylor Fausak
        twitter_id: 204457677
    title: taylor.fausak.me
    url: 'http://taylor.fausak.me'
